A Research Proposal for the Collaborative Research Course
=========================================================
Benjamin Snow and Oliver Bott

###Introduction




Looking at institutional setting to examine different types and levels of innovation

Steps to undergo:

1.Taking available countries and their innovation data (from innovation index)
Incremental vs radical innovation – we have a proxie variable for high tech innovation
or 
Some other variable which we use to reflect either the presence of innovation, or type of innovation (incremental vs. radical).


2.Tag them into some sort of ‘CME vs LME’  (0 to 1 variable, or 1-4 with some threshold, or use each individual component)
from Soskice framework.

- Industrial relations system  - find proxie
- Education and training systems - find proxie
- System governing intercompany relations - find proxie
- System of company financing and corporate governance - find proxie

or

(Capser et al. p. 204) 

- Labour law. – find proxy variable
- Company law – find proxy variable
- Skill formation – strong vs weak. – find proxie
- Financial


Goal: Measure Innovation in 'CME vs LME' framekwork to examine effect of institutional setting on innovation level and type. 
We want to challenge the VoC framework and analyse to what extent the theory can in fact account for a country´s specialisation either in incremental or radical innovation.

Research Question:
**Does the institutional framework (Coordinated vs Liberal Market Economy) effect innovation level and type?**

### Theoretical background

##Varieties of Capitalism

The Varieties of Capitalism (VoC) framework developed by Hall and Soskice (2001) analyzes different types of capitalist economies. By focusing on the firm-level and strategic interactions between market actors the authors go beyond hitherto dominant theories of Modernization, Neo-corporatism and social systems of production. Taylor, 2009, p.224: "At its most basic level, it is a theory of capitalism by gradation: some countries use markets more than others to cooridnate economic actors this variation is used to explain a myriad of comparative and international political-economic behavior."

Hall and Soskice (2001) use an actor-centred approach by moving big firms and strategic actors into the focus of their analysis. They argue that the success of firms depends on their ability to coordinate effectively with a wide range of actors in five different spheres, i.e. (1) the industrial relations, wage and productivity which affects how wages are determined, (2) vocational and training, (3) corporate governance and the relationship between managers and investors, (4) inter-firm relations and (5) relations with employees.

These spheres make up the institutional framework that firms operate in. Hall and Soskice (2001) argue that firms utilize a given institutional framework strategically and thereby keep it in equilibrium. Institutions are defined as set of rules, formal or informal, that actors generally follow - hence markets are also seen as institutions.

##Explanation of CME and LME differences
In their analysis Hall and Soskice (2001) distinguish between two capitalist economic systems, i.e. liberal market economies (LMEs) and coordinated market economies (CMEs). Each of these ideal types features a distinct institutional framework. Hall and Soskice show how firms resolve coordination problems within the five institutional spheres differently depending on whether they operate in CMEs or LMEs.

In LMEs, where coordination relies mainly on market mechanisms, the relation between demand and supply resolve coordination problems. Firms are attentive to current earnings and the price of their shares on equity markets. Industrial relations are organized through unilateral control coming from top down management. Market competition affects wages and inflation. The education and training system focuses on general skills than can be used flexibly. Economic acitivity is highest in the service sector. LMEs are also characterized by strong antitrust laws. Technology transfer happens mostly through the mobility of employees. Example countries as identified by Hall and Soskice (2001) are the USA, UK, Australia, Canada, New Zealand and Ireland.

CMEs, in contrast, rely on strategic interaction between firms, thereby keeping the system in equilibrium. In the financial system, investment is usually encouraged through the sharing of informal information between firms and associations, reputation and trust play a crucial role. In top management, decision making is based on multilateral action. The industrial relations system is characterised through industry-level bargaining. The education and training system depends on high industry-specific knowledge, which is why CMEs tend to produce elaborate vocational training systems. In inter-company relations, firms tend to undertake joint research, in which cooperation is common.
Examples for CMEs are Germany, Japan, Switzerland, the Netherlands, Sweden, Norway, Denmark, Finland and Austria.

##VoC and innovation
The VoC theory claims that the level of coordination within a certain polity, enabled by the particular institutional setting, determines whether countries tend to produce certain types of innovation. Soskice (1999) argued that the particular production system evolving through a given institutional framework determines the "comparative institutoinal advantage" of an economy, a theory closely related to that of VoC. Soksice (1999) argues that the coordinating capacity of businesses influences the feasibility of different production regimes. CMEs, according to Soskice (1999, p.106), "permit industry-defined unions, technology transfer and diffusion within the industry, technical norm setting within the industry, as well as training of engineers and other high-level specalists within an industry technology framework, and industry-based developments of vocational training standards". It follows that CMEs have a comparative institutional advantage in incremental innovation particularly in manufacturing. LMEs, in contrast, build on market deregulation and favor shorter-term and more competitive relations. Accordingly, LMEs have an advantage in producing radical innovation particularly in the service sector.


## Methodology

Here is a quick overview of how to load data into R. 

*Load data from user folder*

OECD_Cities_Pat <- read.csv("Data/OECD_Cities_Pat.csv")

OECD_Cities_Pop <- read.csv("Data/OECD_Cities_Pop.csv")

Destatis_Pat <- read.csv("Data/Destatis_Pat.csv")

Destatis_Pat_Simple2 <- read.csv("Data/Destatis_Pat_Simple2.csv")


*Load data from web*

Patent_data <- read.csv('http://vincentarelbundock.github.io/Rdatasets/csv/Ecdat/PatentsHGH.csv')


*Load patent data from Worldbank*

install.packages("WDI")

library(WDI)

Patents_WB <- WDI(indicator = 'SP.POP.SCIE.RD.P6')

*We can now pull data straight from the OECD website*

install.packages("devtools")
require("devtools")
install_github("rsdmx", "opensdmx")
library("rsdmx")

dataURL <- "http://stats.oecd.org/restsdmx/sdmx.ashx/GetData/CITIES/DEU+DE001+DE002+DE003+DE004+DE005+DE006+DE007+DE008+DE009+DE010+DE011+DE012+DE013+DE014+DE015+DE027+DE033+DE034+DE035+DE040+DE501+DE502+DE504+DE507.PCT_INTENSITY?startTime=2000&endTime=2012"
sdmx <- readSDMX(dataURL)
stats <- as.data.frame(sdmx)


