### Open vs. closed access to knowledge: Using online network data to measure innovation
============

## Introduction

> Object and Importance of the Study

Policy makers worldwide have a profound interest in innovation for its significance for the creation of wealth and economic security. @taylor2004 views innovation as "the driving force behind modern economic growth, relative industrial power, and competitive advantage" (p.222). @schumpeter1942 greatly shaped the innovation discourse with the concept of structural change and the business cycle, the process he termed "creative destruction". Numerous studies, for example the Innovation Union Scoreboard[^IUS] and the OECD Science, Technology and Innovation Scoreboard[^STI], have attempted to measure and compare the innovation performance on the national level.  However, most examinations of innovation have usilized national level patent data, relying on this form of registering of proprietary data as a means of measuring innovation.  This leaves largely unexplored other, more open measures of innovation. The relatively recent emergence of network-based research systems offer new and potentially more instructive metrics by which to measure innovation, compared to protected closed knowledge. 

This research project examines the potential preferability of using collaborative online network data on the city-level as an innovation indicator. By doing so, this work will critically assess current innovation indicators in the hope of offering new alternatives for measuring and understanding innovation. Since @freeman2009, among other scholars, called for the continuous improvement of innovation measurement, this work seeks to go beyond the widespread use of patent data to contribute to the refinement of innovation indicators, and the field as a whole.

## State of the Field

**Defining Innovation**

Using a rather grand view in his understanding of innovation, @schumpeter1942 sees innovation as "a process of industrial mutation, that incessantly revolutionizes the economic structure from within, incessantly destroying the old one, incessantly creating a new one". In a more understated characterization, @smith2005 defines innovation as "the creation of something qualitatively new, via processes of learning and knowledge building. It involves changing competences and capabilities, and producing qualitatively new performance outcomes" [@smith2005, 149]. While it is widely accepted that innovation can take many forms, e.g. product, process, marketing and proccess innovations, @frankelius2009, in his extensive literature review of innovation studies, criticizes the widespread underlying assumption that innovation is limited to technological innovation. While accepting @frankelius2009's critique of innovation as taking place outside of the technological realm, for the purpose of this study technological innovation, and specifically software innovation, will be the primary focus following relatively closely to @smith2005's definition.

**Measuring Innovation**

> How is innovation measured? Range of indicators, input-throughput-output, difficult to measure. How do we compare innovation performance? Refer to rankings, race for innovation. At what level is it measured? Usually national but this has shortcomings, regional is more pronounced.

The technology focus can partly be explained by the difficulties associated with the measurement of innovation. @smith2005 notes the measuring challenge, as innovation is by definition a novelty and thus commensurability is a demanding task. For these reasons innovation has traditionally though controversially been measured with a focus on inputs, such as personnel and equipment, as well as economic outputs in the form of patents, product output and related revenues [@freeman2009]. 

@smith2005 mentions the development of new indicators, but focuses on country level economic measures, which are helpful for comparability. @

**Limitations of Patent Data**

> Why are patents important? Widely used and accepted as indicator. Comparison of closed/protected vs. open knowledge. Importance of networks for knowledge creation and sharing, complexity of current challenges, growing relevance of collaborations. New quality of networking enabled through new technology and software.

An indicator most often found in innovation research is patent data [see @taylor2004]. A patent is a "temporary legal monopoly granted by the government to an inventor for the commerical use of his or her invention [@taylor2004, 229). A patent constitutes a property right awarded when an invention is shown to be non-trivial, useful, and novel [@taylor2004, 230]. Patents were first used to measure demand-side determinants of innovation by Scherer and Schmookler [REFERENCE], and have been used in the analysis of innovation activity for over three decades [@taylor2004, 230). While long hindered by technological limitations requiring labor intensive patent analysis, recent improvements due to machine-readable patent data have spurred recent econometric analysis, as did for example @hall2005 who analyzed millions of patents.

Despite the usefulness of patent data, @taylor2004 found several limitations to using patents to measure innovation. First, patents suffer from a 'classification problem' as assigning specific industries to patents, as industry of innovation and industry of production can change over time. Additionally, patents may vary widely in significance, both technically and economically [@taylor2004, 231]. Most significantly for the purpose on this study, @taylor2004 as well as @pakes1980 found that “patents are a flawed measure particularly since not all new innovations are patented and since patents differ greatly in their economic impact” (p.378). Thus, while for some considerable time patents have been considered to be the most effective proxy with which to measure innovation, even recent studies have begun to examine alternatives due to patents limitations in measuring innovation. This is why for example @taylor2004 also used publication data as an innovation proxy.

Both data on patents and academic publishing include only proprietary or closed forms of innovation, in the same manner that @taylor2004 finds that 'not all inventions are patentable', not all innovation needs to be an invention.  Taylor notes this point implicitly in searching for a way to weight the size of innovation from one published paper to the next. @taylor2004 uses paper citations as a measure to weight the size of an innovation. 

Despite these efforts, current developments in research indicate that „characteristics that were important last century may well no longer be so relevant today and indeed may even be positively misleading“ [@freeman2009, 3]. Today we witness a shift away from the belief that innovation only occurs in professional R&D labs, a change towards what @freeman2009 calls "research without frontiers" (p.13). Even though networks and research collaborations become increasingly important, there have been relatively few studies focusing on network data [see for example @breschi2005]. Even where research networks have been analysed, the focus is too often on economically useful knowledge [see @acs2002]. Other studies focusing on research networks focus on other protected collaborative networks [see @ponds2010].

Similarly, for this study we will be using the association of a contributor, but rather based around their reputation, and not their works citation level (**THIS SHOULD GO INTO DESIGN**).

**Using Network Data as Innovation Indicator**

> Exploration of relationship between patent and network data. (Currently networks are mainly analyzed by looking into paper citations, researchers' mobility). Innovation does not necessarily take place in firms, outcome not protected but accessible. Interesting questions: What is their relationship? What are the differences? Is there a potential lag between the two?

Since @freeman2009 among others called for the continuous improvement of innovation measurement, this work seeks to contribute to the refinement of innovation indicators. The purpose of this study is to explore the conceptual and statistical viability of a new metric by which we can measure innovation. New metrics are needed, because "too much energy has gone into squeezing the last bit of juice out of old data collected for different purposes relative to the design of new types of data" (Kenneth Arrow, quoted from Smith 2005, p. 148).

**Intended Data Sources**

> Identification and sorting of intended data sources, their format, and overall plan for cleaning and analysis

For examining open network data against patent data, this study uses patent at the city level, taken from the Organization for Economic Co-operation and Development, available at http://stats.oecd.org. Patent data was taken for 20 cities overall, ranging from six different countries, including their country level patent data, for general comparison.  Additional data taken from the OECD include GDP per capita data and environmental data, as other variables which could prove significant in explaining differences in innovation.

This OECD data's format is in ( ).  To clean this data for effective statistical comparison, the deletion of several empty rows, and the renaming of relevant variables with their city name rather than an attributed code, for clarity.  Past this, all datasets must be effectively merged.

To examine open data innovation, data was obtained from the Application Programming Interface (commonly known as an API) of the git repository web-based hosting service Github (Github.com). Github's use of distributed revision control and source code management make it a commonly used software development collaboration tool. The ability to see 


**Preliminary Statistics**

> Early statistical analysis findings and expected types of statistical analysis based upon nature of datasets used


## Research question
- Does the anlaysis of research networks function as an indicator to measure local level innovation performance?
- Is network analysis superior to patent analysis in order to measure innovation performance?

[^IUS]: For the latest edition see [http://ec.europa.eu/enterprise/policies/innovation/policy/innovation-scoreboard/index_en.htm]
[^STI]: For the latest edition see [http://www.oecd.org/sti/scoreboard.htm]
